name: Build Unity WebGL

on:
  push:
    branches:
      - prod

jobs:
  build-for-webgl:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Cache Unity Packages
        uses: actions/cache@v3
        with:
          path: Library
          key: ${{ runner.os }}-unity-packages-${{ hashFiles('**/Packages/manifest.json') }}
          restore-keys: |
            ${{ runner.os }}-unity-packages-

      # 3. Activate Unity (requires license file or manual credentials)
    #   - name: Activate Unity License
    #     uses: game-ci/unity-activate@v2
    #     with:
    #       unityVersion: 2022.3.19f1
    #     env:
    #       UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
    #       UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
    #       UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      # 4. Build the project (WebGL target)
      - name: Build WebGL
        uses: game-ci/unity-builder@v4
        env:
            UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
            UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
            UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
        #   unityVersion: docker pull unityci/editor:ubuntu-2022.3.56f1-webgl-3.1.0
          unityVersion: auto
          targetPlatform: WebGL
          # By default, it will look for your .sln or .csproj in your root project folder.
          # If your Unity project is in a subdirectory, specify the path:
          # projectPath: MyUnityProject/
      
      - name: Upload WebGL build
        uses: actions/upload-artifact@v4
        with:
          name: WebGLBuild
          path: build/WebGL
